global:
  domain: "localdomain"
  certificateName:

replicas: 1

image:
  repository: acrdevelopment01.azurecr.io/api-mobile-proxy-collect
  tag: 21660
  pullPolicy: Always

imagePullSecrets:
  - name: creditforce

envFrom:
  - secretRef:
      name: mobile

nameOverride: "api-mobile-v1-proxy-collect"
fullnameOverride: "api-mobile-v1-proxy-collect"

serviceAccount:
  create: true
  annotations: {}
  name: "api-mobile-v1-proxy-collect"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
  className: nginx
  host: "api-mobile-v1-proxy-collect"           # Simple string
  tls:
    enabled: true                           # Simple flag
    secretName: "api-mobile-v1-proxy-collect-tls"  # Simple string

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70

nodeSelector: {}

tolerations: []

affinity: {}
