apiVersion: v2
description: API Workflow Admin chart for Kubernetes
name: workflow-api-scripts
sources:
  - https://creditforce.github.io/helm-chart/
icon:  https://avatars.githubusercontent.com/u/66394013
version: 1.0.5
appVersion: "0.0.1"
