apiVersion: v2
description: engine notification hub chart for Kubernetes
name: engine-notification-hub
sources:
  - https://creditforce.github.io/helm-chart/
icon:  https://images8.webydo.com/96/9628253/3958/F6AD13C0-3367-06E4-3434-7E46130909F9.png
version: 1.0.12
appVersion: "0.0.1"
