apiVersion: v2
description: API Rules chart for Kubernetes
name: api-rules
sources:
  - https://creditforce.github.io/helm-chart/
icon:  https://avatars.githubusercontent.com/u/66394013
version: 1.0.2
appVersion: "0.0.1"
