apiVersion: v2
name: cf-flows
version: 1.0.7
description: CreditForce Flows Helm chart for Kubernetes 
sources:
  - https://creditforce.github.io/helm-chart/
icon:  https://images8.webydo.com/96/9628253/3958/F6AD13C0-3367-06E4-3434-7E46130909F9.png
appVersion: "0.0.1"

dependencies:

  - name: api-origin
    version: 1.2.3
    repository: "file://../api-origin/"
    condition: api-origin.enabled

  - name: api-cf-store
    version: 1.0.1
    repository: "file://../api-cf-store/"
    condition: api-cf-store.enabled

  - name: web-cf-origin
    version: 1.0.3
    repository: "file://../web-cf-origin/"
    condition: web-cf-origin.enabled
