apiVersion: v2
description: API auth chart for Kubernetes
name: api-auth
sources:
  - https://creditforce.github.io/helm-chart/
icon:  https://images8.webydo.com/96/9628253/3958/F6AD13C0-3367-06E4-3434-7E46130909F9.png
version: 1.1.3
appVersion: "0.0.1"
