apiVersion: v2
description: API Rules Engine chart for Kubernetes
name: api-rules-engine
sources:
  - https://creditforce.github.io/helm-chart/
icon:  https://avatars.githubusercontent.com/u/66394013
version: 1.0.3
appVersion: "0.0.1"
